CREATE TABLE laptop (
    laptop_id INT AUTO_INCREMENT PRIMARY KEY,
    cpu VARCHAR(100),
    ram VARCHAR(50),
    hard_drive VARCHAR(100),
    gpu VARCHAR(100),
    screen_size DECIMAL(4,1),
    ports VARCHAR(500),
    audio VARCHAR(100),
    keyboard VARCHAR(50),
    lan VARCHAR(50),
    wifi VARCHAR(50),
    bluetooth VARCHAR(50),
    webcam VARCHAR(50),
    operating_system VARCHAR(50),
    battery VARCHAR(50),
    weight DECIMAL(4,2),
    color VARCHAR(50),
    dimensions VARCHAR(100)
);
